help: ## Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend: ## Installing Frontend Component
	@echo installing Frontend
cart: ## Installing Cart Component
	@echo installing Cart
catalogue: ## Installing Catalogue Component
	@echo installing Catalogue
mongodb: ## Installing MongoDB Component
	@echo installing Mongodb
mysql: ## Installing Mysql Component
	@echo installing Mysql
payment: ## Installing Payment Component
	@echo installing Payment
rabbitmq: ## Installing Rabbitmq Component
	@echo installing Rabbitmq
redis: ## Installing Redis Component
	@echo installing Redis
shipping: ## Installing Shipping Component
	@echo installing Shipping
user: ## Installing User Component
	@echo installing User
databases: mongodb mysql redis rabbitmq  ## Installs all Databases
